//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizComputation_490_Model.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int profileID { get; set; }
        public Nullable<int> userID { get; set; }
        public string profileContent { get; set; }
        public string aadharCard { get; set; }
        public string Marksheet12 { get; set; }
        public string Marksheet10 { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
